const session = JSON.parse(localStorage.getItem('compralatino-session') || 'null');
const activeSession = session || { username: '', firstName: '', lastName: '', role: '' };
const page = document.body.dataset.adminPage;
const isAdmin = session?.role === 'admin';
const isSeller = session?.role === 'seller';

if (!session || (!isAdmin && !isSeller)) window.location.replace('/');
if (isSeller && !['ventas', 'productos'].includes(page)) window.location.replace('/administracion/ventas');

const titles = {
  panel: ['Panel ejecutivo', 'Visión operativa de la plataforma en tiempo real.'],
  usuarios: ['Usuarios y vendedores', 'Crea vendedores y administra las cuentas registradas.'],
  productos: ['Gestión de productos', 'Agrega, modifica o retira productos del catálogo.'],
  ventas: ['Gestión de ventas', 'Registra ventas y consulta su historial completo.'],
  analiticas: ['Analíticas', 'Resumen de rendimiento comercial y comportamiento de pujas.'],
  transacciones: ['Transacciones', 'Consulta los movimientos recientes de la plataforma.'],
  salud: ['Salud de API', 'Estado de los servicios conectados.'],
  reportes: ['Reportes', 'Prepara resúmenes operativos para el equipo.'],
  configuracion: ['Configuración', 'Preferencias generales de la plataforma.']
};

function navLink(key, label, href, icon) { return `<a href="${href}" class="${page === key ? 'active' : ''}"><span>${icon}</span>${label}</a>`; }
function navigation() {
  const adminItems = [
    navLink('panel', 'Panel', '/administracion', '▦'), navLink('usuarios', 'Usuarios y vendedores', '/administracion/usuarios', '♙'),
    navLink('ventas', 'Ventas', '/administracion/ventas', '$'), navLink('productos', 'Productos', '/administracion/productos', '□'),
    navLink('analiticas', 'Analíticas', '/administracion/analiticas', '⌁'), navLink('transacciones', 'Transacciones', '/administracion/transacciones', '▤'),
    navLink('salud', 'Salud de API', '/administracion/salud-api', '♡'), navLink('reportes', 'Reportes', '/administracion/reportes', '▥'),
    navLink('configuracion', 'Configuración', '/administracion/configuracion', '⚙')
  ];
  const sellerItems = [navLink('ventas', 'Ventas', '/administracion/ventas', '$'), navLink('productos', 'Productos', '/administracion/productos', '□')];
  return `<aside class="dashboard-sidebar"><a class="brand" href="/"><span class="brand-mark">CL</span><span>Compra<span>Latino</span></span></a><p class="sidebar-role">${isSeller ? 'PORTAL DE VENTAS' : 'ADMINISTRACIÓN'}</p><nav>${(isAdmin ? adminItems : sellerItems).join('')}</nav><section class="sidebar-account"><span>Sesión activa</span><b>${escapeHtml(activeSession.firstName)} ${escapeHtml(activeSession.lastName)}</b><small>${isSeller ? 'Vendedor' : 'Administrador'}</small><button id="logoutButton" class="sidebar-logout">Cerrar sesión</button><a class="sidebar-home" href="/">← Volver al catálogo</a></section></aside>`;
}
function dashboardContent() {
  return `<section class="metrics" id="dashboardMetrics"><article class="metric"><p>Cargando datos</p><strong>—</strong><span>Actualizando</span></article></section>
  <section class="dashboard-panels"><article class="trend-panel"><div class="panel-title"><h3>Tendencia de pujas diarias</h3><span><i></i> Últimos 7 días</span></div><div class="chart-wrap"><span class="axis a1">250</span><span class="axis a2">200</span><span class="axis a3">150</span><span class="axis a4">100</span><span class="axis a5">50</span><svg viewBox="0 0 560 165" preserveAspectRatio="none" aria-label="Gráfica de pujas"><path class="chart-grid" d="M0 8H560M0 43H560M0 78H560M0 113H560M0 148H560"/><polyline class="chart-primary" points="0,119 93,92 186,106 280,57 373,77 466,29 560,47"/><polyline class="chart-secondary" points="0,140 93,131 186,113 280,121 373,94 466,103 560,74"/></svg><div class="chart-days"><span>Lun</span><span>Mar</span><span>Mié</span><span>Jue</span><span>Vie</span><span>Sáb</span><span>Dom</span></div></div></article><article class="health-panel"><div class="panel-title"><h3>Monitor de salud</h3><span class="healthy">● Operativo</span></div><div class="health-item"><div><b>API principal</b><span>99.98%</span></div><i><em style="width:99%"></em></i></div><div class="health-item"><div><b>Base de datos</b><span>99.94%</span></div><i><em style="width:96%"></em></i></div><div class="health-item"><div><b>Servicio de pagos</b><span>99.91%</span></div><i><em style="width:92%"></em></i></div></article></section>
  <section class="transactions"><div class="panel-title"><h3>Transacciones recientes</h3><span>Ver todas →</span></div><div class="transactions-table"><div class="transaction-row header"><span>ID</span><span>Usuario</span><span>Artículo</span><span>Total</span><span>Estado</span><span>Fecha</span></div><div class="transaction-row"><span>TXN-1023</span><span>clienteDemo</span><span>Reloj Seiko vintage</span><span>$236</span><b class="completed">Completada</b><span>Hoy</span></div><div class="transaction-row"><span>TXN-1024</span><span>maria88</span><span>Consola retro</span><span>$142</span><b class="pending">Pendiente</b><span>Hoy</span></div><div class="transaction-row"><span>TXN-1025</span><span>carlos_vega</span><span>Cámara Fujifilm</span><span>$896</span><b class="completed">Completada</b><span>Ayer</span></div></div></section>`;
}
function productsContent() { return `<section class="admin-content-grid product-admin-grid"><section class="page-card"><p class="eyebrow">CATÁLOGO</p><h3 id="productFormTitle">Agregar producto</h3><p id="productFormDescription">Publica un nuevo producto en el catálogo.</p><form id="productForm" class="form-stack admin-form"><div class="split-fields"><span><label for="productTitle">Título</label><input id="productTitle" required></span><span><label for="productCategory">Categoría</label><input id="productCategory" required></span></div><div class="split-fields three-fields"><span><label for="productPrice">Precio (USD)</label><input id="productPrice" type="number" min="0" step="0.01" required></span><span><label for="productBid">Oferta actual</label><input id="productBid" type="number" min="0" step="0.01" required></span><span><label for="productShipping">Envío</label><input id="productShipping" type="number" min="0" step="0.01" value="0" required></span></div><label for="productImage">URL de imagen</label><input id="productImage" type="url" placeholder="https://..."><label for="productBadge">Etiqueta</label><input id="productBadge" value="Disponible" required><div class="form-button-row"><button id="productSubmit" class="primary-button" type="submit">Agregar producto</button><button id="productCancel" class="text-button" type="button" hidden>Cancelar edición</button><button id="productDelete" class="danger-button" type="button" hidden>Eliminar producto</button></div><p id="productFeedback" class="form-feedback" aria-live="polite"></p></form></section><section class="page-card product-directory"><p class="eyebrow">INVENTARIO</p><h3>Productos registrados</h3><p>Selecciona un producto para editarlo o eliminarlo del catálogo.</p><label class="user-search" for="productSearch"><span>Buscar producto</span><input id="productSearch" type="search" placeholder="Título o categoría" autocomplete="off"></label><p id="productSearchStatus" class="user-search-status" aria-live="polite"></p><div id="productList" class="user-list product-list"></div></section></section>`; }
function salesContent() { return `<section class="admin-content-grid sales-admin-grid"><section class="page-card"><p class="eyebrow">NUEVA VENTA</p><h3>Registrar venta</h3><p>Asocia la operación con un cliente y un producto. El cliente la verá en su historial.</p><form id="saleForm" class="form-stack admin-form"><label for="saleCustomer">Cliente</label><select id="saleCustomer" required></select><label for="saleProduct">Producto</label><select id="saleProduct" required></select><div class="split-fields three-fields"><span><label for="saleQuantity">Cantidad</label><input id="saleQuantity" type="number" min="1" step="1" value="1" required></span><span><label for="saleUnitPrice">Precio unitario</label><input id="saleUnitPrice" type="number" min="0" step="0.01" required></span><span><label for="saleShipping">Envío</label><input id="saleShipping" type="number" min="0" step="0.01" value="0" required></span></div><div class="split-fields"><span><label for="saleServiceFee">Cargo de servicio</label><input id="saleServiceFee" type="number" min="0" step="0.01" value="0" required></span><span><label for="saleStatus">Estado</label><select id="saleStatus"><option value="paid">Pagada</option><option value="shipped">Enviada</option><option value="delivered">Entregada</option><option value="cancelled">Cancelada</option></select></span></div><label for="saleNotes">Notas</label><textarea id="saleNotes" maxlength="500" rows="3" placeholder="Información opcional de la venta"></textarea><div class="sale-total"><span>Total calculado</span><strong id="saleTotal">$0.00</strong></div><button class="primary-button" type="submit">Registrar venta</button><p id="saleFeedback" class="form-feedback" aria-live="polite"></p></form></section><section class="page-card sales-history-card"><p class="eyebrow">HISTORIAL</p><h3>Todas las ventas</h3><p>Operaciones registradas por vendedores y administradores.</p><label class="user-search" for="saleSearch"><span>Buscar venta</span><input id="saleSearch" type="search" placeholder="Cliente, producto o vendedor" autocomplete="off"></label><p id="saleSearchStatus" class="user-search-status" aria-live="polite"></p><div id="salesList" class="sales-list"></div></section></section>`; }
function usersContent() { return `<section class="admin-content-grid"><section class="page-card"><p class="eyebrow">GESTIÓN DE CUENTAS</p><h3 id="userFormTitle">Crear usuario</h3><p id="userFormDescription">Registra usuarios, vendedores y administradores.</p><form id="userForm" class="form-stack admin-form"><div class="split-fields"><span><label for="newUsername">Nombre de usuario</label><input id="newUsername" minlength="4" required></span><span><label for="newEmail">Correo</label><input id="newEmail" type="email" required></span></div><div class="split-fields"><span><label for="newFirstName">Nombre</label><input id="newFirstName" required></span><span><label for="newLastName">Apellidos</label><input id="newLastName" required></span></div><div class="split-fields"><span><label for="newPhone">Número celular</label><input id="newPhone"></span><span><label for="newBirthDate">Fecha de nacimiento</label><input id="newBirthDate" type="date"></span></div><label for="newRole">Rol</label><select id="newRole"><option value="seller">Vendedor</option><option value="customer">Usuario</option><option value="admin">Administrador</option></select><p id="protectedPasswordNotice" class="protected-password-notice" hidden>La contraseña está protegida y nunca se muestra. Solo cambiará si escribes una nueva durante la edición.</p><section id="userPasswordEditor" class="user-password-editor"><label id="newPasswordLabel" for="newPassword">Contraseña</label><div class="password-field"><input id="newPassword" type="password" autocomplete="new-password" minlength="8" required><button type="button" class="password-toggle" data-user-password="newPassword">Mostrar</button></div><label id="repeatPasswordLabel" for="repeatPassword">Repetir contraseña</label><div class="password-field"><input id="repeatPassword" type="password" autocomplete="new-password" minlength="8" required><button type="button" class="password-toggle" data-user-password="repeatPassword">Mostrar</button></div><small id="userPasswordHint">Usa al menos 8 caracteres.</small></section><button id="userSubmit" class="primary-button" type="button">Crear usuario</button><button id="cancelUserEdit" class="text-button" type="button" hidden>Cancelar edición</button><p id="userFeedback" class="form-feedback" aria-live="polite"></p></form></section><section class="page-card user-directory"><p class="eyebrow">DIRECTORIO</p><h3>Usuarios registrados</h3><p>Selecciona directamente una cuenta para consultar o actualizar su información.</p><label class="user-search" for="userSearch"><span>Buscar usuario</span><input id="userSearch" type="search" placeholder="Nombre, usuario o correo" autocomplete="off"></label><p id="userSearchStatus" class="user-search-status" aria-live="polite"></p><div id="userList" class="user-list"></div></section></section>`; }
function infoContent() { const content = { analiticas:['Rendimiento de pujas','Las pujas activas crecieron 8.2% frente al período anterior.'], transacciones:['Historial de transacciones','Consulta las operaciones procesadas, pendientes y completadas.'], salud:['Servicios disponibles','Todos los servicios principales están operativos.'], reportes:['Reportes operativos','Genera el corte mensual de ventas y actividad.'], configuracion:['Preferencias de plataforma','Las preferencias de notificaciones y operaciones se administrarán desde aquí.'] }[page]; return `<section class="page-card info-card"><p class="eyebrow">${titles[page][0].toUpperCase()}</p><h3>${content[0]}</h3><p>${content[1]}</p><div class="info-stat"><strong>${page === 'salud' ? '99.98%' : page === 'analiticas' ? '+12.5%' : 'Listo'}</strong><span>${page === 'salud' ? 'Disponibilidad de servicios' : 'Información actualizada'}</span></div></section>`; }
function mainContent() { if (page === 'panel') return dashboardContent(); if (page === 'productos') return productsContent(); if (page === 'ventas') return salesContent(); if (page === 'usuarios') return usersContent(); return infoContent(); }

document.querySelector('#adminRoot').innerHTML = `<section class="executive-dashboard admin-page">${navigation()}<section class="dashboard-main"><header class="dashboard-topbar"><div><h2>${titles[page][0]}</h2><p>${titles[page][1]}</p></div></header>${mainContent()}</section></section>`;

function headers(json = false) { const value = { 'x-compralatino-user': activeSession.username }; if (json) value['Content-Type'] = 'application/json'; return value; }
document.querySelector('#logoutButton').addEventListener('click', () => { localStorage.removeItem('compralatino-session'); window.location.assign('/'); });

async function loadDashboard() { const response = await fetch('/api/dashboard', { headers: headers() }); if (!response.ok) return; const data = await response.json(); document.querySelector('#dashboardMetrics').innerHTML = data.metrics.map((metric) => `<article class="metric"><p>${metric.label}</p><strong>${metric.value}</strong><span>↑ ${metric.delta}</span></article>`).join(''); }
let productsCache = [];
let selectedProduct = null;
function productPayload() { return { title: document.querySelector('#productTitle').value, category: document.querySelector('#productCategory').value, price: Number(document.querySelector('#productPrice').value), currentBid: Number(document.querySelector('#productBid').value), shipping: Number(document.querySelector('#productShipping').value), image: document.querySelector('#productImage').value, badge: document.querySelector('#productBadge').value }; }
function resetProductForm() { selectedProduct = null; document.querySelector('#productForm').reset(); document.querySelector('#productShipping').value = 0; document.querySelector('#productBadge').value = 'Disponible'; document.querySelector('#productFormTitle').textContent = 'Agregar producto'; document.querySelector('#productFormDescription').textContent = 'Publica un nuevo producto en el catálogo.'; document.querySelector('#productSubmit').textContent = 'Agregar producto'; document.querySelector('#productCancel').hidden = true; document.querySelector('#productDelete').hidden = true; document.querySelector('#productFeedback').textContent = ''; renderProductList(); }
function selectProduct(product) { selectedProduct = product; document.querySelector('#productTitle').value = product.title; document.querySelector('#productCategory').value = product.category; document.querySelector('#productPrice').value = product.price; document.querySelector('#productBid').value = product.currentBid; document.querySelector('#productShipping').value = product.shipping; document.querySelector('#productImage').value = product.image || ''; document.querySelector('#productBadge').value = product.badge || ''; document.querySelector('#productFormTitle').textContent = 'Editar producto'; document.querySelector('#productFormDescription').textContent = 'Actualiza la información visible en el catálogo.'; document.querySelector('#productSubmit').textContent = 'Guardar cambios'; document.querySelector('#productCancel').hidden = false; document.querySelector('#productDelete').hidden = false; document.querySelector('#productFeedback').textContent = ''; renderProductList(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderProductList() { const list = document.querySelector('#productList'); if (!list) return; const query = normalizeUserSearch(document.querySelector('#productSearch').value); const products = productsCache.filter((product) => !query || normalizeUserSearch(`${product.title} ${product.category}`).includes(query)); document.querySelector('#productSearchStatus').textContent = `${products.length} producto${products.length === 1 ? '' : 's'}`; list.innerHTML = products.length ? products.map((product) => `<button class="user-item${selectedProduct?.id === product.id ? ' selected' : ''}" type="button" data-product="${escapeHtml(product.id)}"><span><b>${escapeHtml(product.title)}</b><span>${escapeHtml(product.category)} · ${money(product.price)}</span></span><span class="user-item-arrow">→</span></button>`).join('') : '<p class="user-empty">No se encontraron productos.</p>'; list.querySelectorAll('[data-product]').forEach((button) => button.addEventListener('click', () => selectProduct(productsCache.find((product) => product.id === button.dataset.product)))); }
async function refreshProducts() { const response = await fetch('/api/manage/products', { headers: headers() }); productsCache = response.ok ? await response.json() : []; renderProductList(); }
function setupProducts() { document.querySelector('#productSearch').addEventListener('input', renderProductList); document.querySelector('#productCancel').addEventListener('click', resetProductForm); document.querySelector('#productDelete').addEventListener('click', async () => { if (!selectedProduct || !window.confirm(`¿Eliminar ${selectedProduct.title} del catálogo?`)) return; const response = await fetch(`/api/products/${encodeURIComponent(selectedProduct.id)}`, { method: 'DELETE', headers: headers() }); const result = await response.json(); document.querySelector('#productFeedback').textContent = response.ok ? result.message : result.error; if (response.ok) { await refreshProducts(); resetProductForm(); } }); document.querySelector('#productForm').addEventListener('submit', async (event) => { event.preventDefault(); const endpoint = selectedProduct ? `/api/products/${encodeURIComponent(selectedProduct.id)}` : '/api/products'; const response = await fetch(endpoint, { method: selectedProduct ? 'PATCH' : 'POST', headers: headers(true), body: JSON.stringify(productPayload()) }); const result = await response.json(); document.querySelector('#productFeedback').textContent = response.ok ? (selectedProduct ? 'Producto actualizado correctamente.' : 'Producto agregado correctamente.') : result.error; if (response.ok) { await refreshProducts(); resetProductForm(); } }); resetProductForm(); refreshProducts(); }

let salesCache = [];
let saleProducts = [];
function money(value) { return new Intl.NumberFormat('es-SV', { style: 'currency', currency: 'USD' }).format(Number(value || 0)); }
function saleStatusLabel(status) { return ({ paid: 'Pagada', shipped: 'Enviada', delivered: 'Entregada', cancelled: 'Cancelada' })[status] || status; }
function updateSaleTotal() { const quantity = Number(document.querySelector('#saleQuantity').value || 0); const unitPrice = Number(document.querySelector('#saleUnitPrice').value || 0); const shipping = Number(document.querySelector('#saleShipping').value || 0); const service = Number(document.querySelector('#saleServiceFee').value || 0); document.querySelector('#saleTotal').textContent = money((quantity * unitPrice) + shipping + service); }
function fillSaleProduct() { const product = saleProducts.find((item) => item.id === document.querySelector('#saleProduct').value); if (!product) return; document.querySelector('#saleUnitPrice').value = product.price; document.querySelector('#saleShipping').value = product.shipping; updateSaleTotal(); }
function renderSales() { const query = normalizeUserSearch(document.querySelector('#saleSearch').value); const sales = salesCache.filter((sale) => !query || normalizeUserSearch(`${sale.customer.firstName} ${sale.customer.lastName} ${sale.customer.username} ${sale.product.title} ${sale.seller?.firstName || ''} ${sale.seller?.lastName || ''}`).includes(query)); document.querySelector('#saleSearchStatus').textContent = `${sales.length} venta${sales.length === 1 ? '' : 's'} registrada${sales.length === 1 ? '' : 's'}`; document.querySelector('#salesList').innerHTML = sales.length ? sales.map((sale) => `<article class="sale-item"><div><b>${escapeHtml(sale.product.title)}</b><span>${escapeHtml(sale.customer.firstName)} ${escapeHtml(sale.customer.lastName)} · @${escapeHtml(sale.customer.username)}</span></div><div class="sale-item-meta"><strong>${money(sale.total)}</strong><span class="sale-status status-${escapeHtml(sale.status)}">${saleStatusLabel(sale.status)}</span></div><footer><span>${new Date(sale.createdAt).toLocaleString('es-SV')}</span><span>Vendedor: ${escapeHtml(sale.seller?.firstName || '—')} ${escapeHtml(sale.seller?.lastName || '')}</span></footer></article>`).join('') : '<p class="user-empty">No hay ventas registradas con ese criterio.</p>'; }
async function loadSales() { const response = await fetch('/api/sales', { headers: headers() }); salesCache = response.ok ? await response.json() : []; renderSales(); }
async function setupSales() { const [customersResponse, productsResponse] = await Promise.all([fetch('/api/customers', { headers: headers() }), fetch('/api/products')]); const customers = customersResponse.ok ? await customersResponse.json() : []; saleProducts = productsResponse.ok ? await productsResponse.json() : []; document.querySelector('#saleCustomer').innerHTML = customers.map((customer) => `<option value="${escapeHtml(customer.id)}">${escapeHtml(customer.firstName)} ${escapeHtml(customer.lastName)} (@${escapeHtml(customer.username)})</option>`).join(''); document.querySelector('#saleProduct').innerHTML = saleProducts.map((product) => `<option value="${escapeHtml(product.id)}">${escapeHtml(product.title)}</option>`).join(''); document.querySelector('#saleProduct').addEventListener('change', fillSaleProduct); ['saleQuantity', 'saleUnitPrice', 'saleShipping', 'saleServiceFee'].forEach((id) => document.querySelector(`#${id}`).addEventListener('input', updateSaleTotal)); document.querySelector('#saleSearch').addEventListener('input', renderSales); document.querySelector('#saleForm').addEventListener('submit', async (event) => { event.preventDefault(); const payload = { customerId: document.querySelector('#saleCustomer').value, productId: document.querySelector('#saleProduct').value, quantity: Number(document.querySelector('#saleQuantity').value), unitPrice: Number(document.querySelector('#saleUnitPrice').value), shippingFee: Number(document.querySelector('#saleShipping').value), serviceFee: Number(document.querySelector('#saleServiceFee').value), status: document.querySelector('#saleStatus').value, notes: document.querySelector('#saleNotes').value }; const response = await fetch('/api/sales', { method: 'POST', headers: headers(true), body: JSON.stringify(payload) }); const result = await response.json(); document.querySelector('#saleFeedback').textContent = response.ok ? 'Venta registrada y agregada al historial del cliente.' : result.error; if (response.ok) { document.querySelector('#saleForm').reset(); document.querySelector('#saleQuantity').value = 1; document.querySelector('#saleServiceFee').value = 0; fillSaleProduct(); await loadSales(); } }); fillSaleProduct(); await loadSales(); }
const userFieldIds = ['newUsername', 'newEmail', 'newFirstName', 'newLastName', 'newPhone', 'newBirthDate', 'newRole'];
let userMode = 'create';
let selectedUser = null;
let usersCache = [];

function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
function roleLabel(role) { return role === 'seller' ? 'Vendedor' : role === 'admin' ? 'Administrador' : 'Usuario'; }
function normalizeUserSearch(value) { return String(value || '').trim().toLocaleLowerCase('es'); }
function clearUserPasswords() { ['newPassword', 'repeatPassword'].forEach((id) => { const input = document.querySelector(`#${id}`); input.value = ''; input.type = 'password'; }); document.querySelectorAll('[data-user-password]').forEach((button) => { button.textContent = 'Mostrar'; }); }
function fillUser(user) { document.querySelector('#newUsername').value = user?.username || ''; document.querySelector('#newEmail').value = user?.email || ''; document.querySelector('#newFirstName').value = user?.firstName || ''; document.querySelector('#newLastName').value = user?.lastName || ''; document.querySelector('#newPhone').value = user?.phone || ''; document.querySelector('#newBirthDate').value = user?.birthDate || ''; document.querySelector('#newRole').value = user?.role || 'seller'; clearUserPasswords(); }
function setUserMode(mode) {
  userMode = mode;
  const creating = mode === 'create';
  const editing = mode === 'editing';
  const selected = mode === 'selected';
  userFieldIds.forEach((id) => { document.querySelector(`#${id}`).disabled = selected; });
  document.querySelector('#userPasswordEditor').hidden = selected;
  document.querySelector('#protectedPasswordNotice').hidden = !selected;
  document.querySelector('#newPassword').required = creating;
  document.querySelector('#repeatPassword').required = creating;
  document.querySelector('#newPasswordLabel').textContent = creating ? 'Contraseña' : 'Nueva contraseña';
  document.querySelector('#repeatPasswordLabel').textContent = creating ? 'Repetir contraseña' : 'Repetir nueva contraseña';
  document.querySelector('#userPasswordHint').textContent = creating ? 'Usa al menos 8 caracteres.' : 'Déjala vacía para conservar la contraseña actual.';
  document.querySelector('#userFormTitle').textContent = creating ? 'Crear usuario' : selected ? 'Detalle del usuario' : 'Editar usuario';
  document.querySelector('#userFormDescription').textContent = creating ? 'Registra usuarios, vendedores y administradores.' : selected ? 'Revisa la información y elige Editar usuario para habilitar los campos.' : 'Actualiza los datos necesarios. La contraseña solo cambia si escribes una nueva.';
  const submit = document.querySelector('#userSubmit');
  submit.textContent = creating ? 'Crear usuario' : selected ? 'Editar usuario' : 'Guardar cambios';
  const cancel = document.querySelector('#cancelUserEdit');
  cancel.hidden = creating;
  cancel.textContent = editing ? 'Cancelar edición' : 'Crear nuevo usuario';
  document.querySelector('#userFeedback').textContent = '';
  document.querySelectorAll('.user-item').forEach((item) => item.classList.toggle('selected', Boolean(selectedUser) && item.dataset.user === selectedUser.username));
  if (editing) document.querySelector('#newUsername').focus();
}
function resetUserForm() { selectedUser = null; document.querySelector('#userForm').reset(); fillUser(null); setUserMode('create'); }
function selectUser(user) { selectedUser = user; fillUser(user); setUserMode('selected'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function renderUserList() {
  const query = normalizeUserSearch(document.querySelector('#userSearch').value);
  const visibleUsers = usersCache.filter((user) => !query || normalizeUserSearch(`${user.firstName} ${user.lastName} ${user.username} ${user.email} ${roleLabel(user.role)}`).includes(query));
  document.querySelector('#userSearchStatus').textContent = query ? `${visibleUsers.length} resultado${visibleUsers.length === 1 ? '' : 's'}` : `${visibleUsers.length} usuario${visibleUsers.length === 1 ? '' : 's'} registrado${visibleUsers.length === 1 ? '' : 's'}`;
  document.querySelector('#userList').innerHTML = visibleUsers.length ? visibleUsers.map((user) => `<button class="user-item${selectedUser?.username === user.username ? ' selected' : ''}" type="button" data-user="${escapeHtml(user.username)}"><span><b>${escapeHtml(user.firstName)} ${escapeHtml(user.lastName)}</b><span>@${escapeHtml(user.username)} · ${roleLabel(user.role)}</span></span><span class="user-item-arrow" aria-hidden="true">→</span></button>`).join('') : '<p class="user-empty">No se encontraron usuarios con ese criterio.</p>';
  document.querySelectorAll('.user-item').forEach((item) => item.addEventListener('click', () => selectUser(usersCache.find((user) => user.username === item.dataset.user))));
}
async function loadUsers(usernameToSelect) {
  const response = await fetch('/api/users', { headers: headers() });
  if (!response.ok) return;
  usersCache = await response.json();
  renderUserList();
  if (usernameToSelect) {
    const user = usersCache.find((item) => item.username === usernameToSelect);
    if (user) selectUser(user);
  }
}
function setupUsers() {
  document.querySelector('#userSearch').addEventListener('input', renderUserList);
  document.querySelectorAll('[data-user-password]').forEach((button) => button.addEventListener('click', () => { const input = document.querySelector(`#${button.dataset.userPassword}`); const visible = input.type === 'text'; input.type = visible ? 'password' : 'text'; button.textContent = visible ? 'Mostrar' : 'Ocultar'; }));
  document.querySelector('#userSubmit').addEventListener('click', () => { if (userMode === 'selected') setUserMode('editing'); else document.querySelector('#userForm').requestSubmit(); });
  document.querySelector('#cancelUserEdit').addEventListener('click', () => { if (userMode === 'editing' && selectedUser) { fillUser(selectedUser); setUserMode('selected'); } else resetUserForm(); });
  document.querySelector('#userForm').addEventListener('submit', async (event) => {
    event.preventDefault();
    if (userMode === 'selected') return;
    const password = document.querySelector('#newPassword').value;
    const passwordConfirmation = document.querySelector('#repeatPassword').value;
    if (password !== passwordConfirmation) { document.querySelector('#userFeedback').textContent = 'Las contraseñas no coinciden.'; return; }
    const payload = { username: document.querySelector('#newUsername').value, email: document.querySelector('#newEmail').value, firstName: document.querySelector('#newFirstName').value, lastName: document.querySelector('#newLastName').value, phone: document.querySelector('#newPhone').value, birthDate: document.querySelector('#newBirthDate').value, role: document.querySelector('#newRole').value };
    if (password) { payload.password = password; payload.passwordConfirmation = passwordConfirmation; }
    const originalUsername = selectedUser?.username;
    const response = await fetch(originalUsername ? `/api/users/${encodeURIComponent(originalUsername)}` : '/api/users', { method: originalUsername ? 'PATCH' : 'POST', headers: headers(true), body: JSON.stringify(payload) });
    const result = await response.json();
    const successMessage = originalUsername ? 'Usuario actualizado correctamente.' : 'Usuario creado correctamente.';
    document.querySelector('#userFeedback').textContent = response.ok ? successMessage : result.error;
    if (!response.ok) return;
    if (originalUsername === activeSession.username) localStorage.setItem('compralatino-session', JSON.stringify(result.user));
    selectedUser = result.user;
    await loadUsers(result.user.username);
    document.querySelector('#userFeedback').textContent = successMessage;
  });
  resetUserForm();
  loadUsers();
}
if (page === 'panel') loadDashboard();
if (page === 'productos') setupProducts();
if (page === 'ventas') setupSales();
if (page === 'usuarios') setupUsers();
