const state = { products: [], saved: new Set(), category: 'Todos', currentUser: JSON.parse(localStorage.getItem('compralatino-session') || 'null'), editingUser: null };
const productGrid = document.querySelector('#productGrid');
const bidDialog = document.querySelector('#bidDialog');
const authDialog = document.querySelector('#authDialog');
const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

function authHeaders(json = false) { const headers = {}; if (json) headers['Content-Type'] = 'application/json'; if (state.currentUser) headers['x-compralatino-user'] = state.currentUser.username; return headers; }
function productCard(product) {
  const node = document.querySelector('#productTemplate').content.cloneNode(true);
  const image = node.querySelector('img'); image.src = product.image; image.alt = product.title;
  node.querySelector('.product-badge').textContent = product.badge; node.querySelector('.product-category').textContent = product.category; node.querySelector('h3').textContent = product.title;
  node.querySelector('.current-bid').textContent = currency.format(product.currentBid); node.querySelector('.bid-count').textContent = `${product.bids} ofertas`; node.querySelector('.ends-in').textContent = `Termina: ${product.endsIn}`;
  const save = node.querySelector('.save-product');
  save.addEventListener('click', () => { state.saved.has(product.id) ? state.saved.delete(product.id) : state.saved.add(product.id); save.classList.toggle('saved'); save.textContent = state.saved.has(product.id) ? '♥' : '♡'; const count = document.querySelector('#savedCount'); count.textContent = state.saved.size; count.style.display = state.saved.size ? 'block' : 'none'; });
  node.querySelector('.bid-button').addEventListener('click', () => openBid(product));
  return node;
}
function renderProducts(products) { productGrid.innerHTML = ''; if (!products.length) { productGrid.innerHTML = '<p>No encontramos productos con esa búsqueda. Prueba otra categoría.</p>'; return; } products.forEach((product) => productGrid.append(productCard(product))); }
async function loadProducts(query = '') { const params = new URLSearchParams(); if (query) params.set('q', query); if (state.category !== 'Todos') params.set('category', state.category); const response = await fetch(`/api/products?${params}`); state.products = await response.json(); renderProducts(state.products); renderProductSelect(); }
function openAuth(view = 'login', message = '') { document.querySelector('#loginPanel').hidden = view !== 'login'; document.querySelector('#registerPanel').hidden = view !== 'register'; document.querySelector('#loginFeedback').textContent = view === 'login' ? message : ''; document.querySelector('#registerFeedback').textContent = view === 'register' ? message : ''; if (!authDialog.open) authDialog.showModal(); }
function openBid(product) { if (!state.currentUser) { window.location.assign(`/acceso?destino=oferta&producto=${encodeURIComponent(product.id)}`); return; } document.querySelector('#bidTitle').textContent = product.title; document.querySelector('#bidCurrent').textContent = `Oferta actual: ${currency.format(product.currentBid)} · ${product.bids} ofertas`; document.querySelector('#bidProductId').value = product.id; const input = document.querySelector('#bidAmount'); input.min = product.currentBid + 1; input.value = product.currentBid + 10; document.querySelector('#bidFeedback').textContent = ''; bidDialog.showModal(); input.focus(); }
function renderRecommendation() { const product = state.products[Math.floor(Math.random() * state.products.length)] || state.products[0]; if (!product) return; document.querySelector('#recommendationProduct').innerHTML = `<article class="featured-card"><img src="${product.image}" alt="${product.title}"><div><p>RECOMENDADO PARA TI</p><h3>${product.title}</h3><strong>${currency.format(product.currentBid)}</strong><button id="featuredBid">Ver subasta →</button></div></article>`; document.querySelector('#featuredBid').addEventListener('click', () => openBid(product)); }
async function loadDashboard() { if (state.currentUser?.role !== 'admin') return; const response = await fetch('/api/dashboard', { headers: authHeaders() }); if (!response.ok) return; const data = await response.json(); document.querySelector('#metrics').innerHTML = data.metrics.map((metric) => `<article class="metric"><p>${metric.label}</p><strong>${metric.value}</strong><span>↑ ${metric.delta}</span></article>`).join(''); }
function updateSessionUI() {
  const isAdmin = state.currentUser?.role === 'admin'; const isSeller = state.currentUser?.role === 'seller'; const accountButton = document.querySelector('#accountButton');
  document.querySelector('#profileNav').hidden = !state.currentUser; document.querySelector('#adminNav').hidden = !isAdmin; document.querySelector('#sellerNav').hidden = !(isAdmin || isSeller); document.querySelector('#admin').hidden = true; document.querySelector('#gestion').hidden = true; document.querySelector('#userManagement').hidden = true;
  accountButton.innerHTML = state.currentUser ? 'Cerrar sesión <span>→</span>' : 'Iniciar sesión <span>→</span>'; accountButton.title = state.currentUser ? `Sesión: ${state.currentUser.username}` : '';
  if (isAdmin) { document.querySelector('#managementEyebrow').textContent = 'GESTIÓN ADMINISTRATIVA'; document.querySelector('#managementTitle').textContent = 'Catálogo, usuarios y vendedores'; loadDashboard(); loadUsers(); } else if (isSeller) { document.querySelector('#managementEyebrow').textContent = 'PANEL DE VENDEDOR'; document.querySelector('#managementTitle').textContent = 'Actualiza productos'; }
}
function setSession(user) { state.currentUser = user; localStorage.setItem('compralatino-session', JSON.stringify(user)); if (user.role === 'admin') { window.location.assign('/administracion'); return; } if (user.role === 'seller') { window.location.assign('/administracion/productos'); return; } updateSessionUI(); }
function logout() { state.currentUser = null; state.editingUser = null; localStorage.removeItem('compralatino-session'); updateSessionUI(); window.location.hash = 'inicio'; }
function passwordStrength(value) { let score = 0; if (value.length >= 8) score += 1; if (/[a-z]/.test(value) && /[A-Z]/.test(value)) score += 1; if (/\d/.test(value)) score += 1; if (/[^A-Za-z0-9]/.test(value)) score += 1; const labels = ['Usa al menos 8 caracteres.', 'Débil', 'Aceptable', 'Fuerte', 'Muy fuerte']; const colors = ['#d6d3ce', '#db4a39', '#e5a43c', '#3b9d76', '#238c6f']; document.querySelector('#strengthBar').style.width = `${score * 25}%`; document.querySelector('#strengthBar').style.background = colors[score]; document.querySelector('#strengthLabel').textContent = labels[score]; }
function renderProductSelect() { const select = document.querySelector('#productSelect'); const selected = select.value; select.innerHTML = state.products.map((product) => `<option value="${product.id}">${product.title}</option>`).join(''); select.value = state.products.some((product) => product.id === selected) ? selected : state.products[0]?.id; fillProductForm(); }
function fillProductForm() { const product = state.products.find((item) => item.id === document.querySelector('#productSelect').value); if (!product) return; document.querySelector('#productTitle').value = product.title; document.querySelector('#productCategory').value = product.category; document.querySelector('#productBid').value = product.currentBid; document.querySelector('#productBadge').value = product.badge; }
async function loadUsers() { const response = await fetch('/api/users', { headers: authHeaders() }); if (!response.ok) return; const users = await response.json(); document.querySelector('#userList').innerHTML = users.map((user) => `<article class="user-item"><div><b>${user.firstName} ${user.lastName}</b><span>@${user.username} · ${user.role === 'seller' ? 'Vendedor' : user.role === 'admin' ? 'Administrador' : 'Usuario'}</span></div><button data-edit-user="${user.username}">Editar</button></article>`).join(''); document.querySelectorAll('[data-edit-user]').forEach((button) => button.addEventListener('click', () => editUser(users.find((user) => user.username === button.dataset.editUser)))); }
function editUser(user) { state.editingUser = user.username; document.querySelector('#newUsername').value = user.username; document.querySelector('#newUsername').disabled = true; document.querySelector('#newEmail').value = user.email; document.querySelector('#newFirstName').value = user.firstName; document.querySelector('#newLastName').value = user.lastName; document.querySelector('#newPhone').value = user.phone || ''; document.querySelector('#newBirthDate').value = user.birthDate || ''; document.querySelector('#newPassword').value = ''; document.querySelector('#newPassword').required = false; document.querySelector('#newRole').value = user.role; document.querySelector('#userSubmit').textContent = 'Guardar usuario'; document.querySelector('#userManagement').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function resetUserForm() { state.editingUser = null; document.querySelector('#userForm').reset(); document.querySelector('#newUsername').disabled = false; document.querySelector('#newPassword').required = true; document.querySelector('#userSubmit').textContent = 'Crear usuario'; }

document.querySelector('#accountButton').addEventListener('click', () => state.currentUser ? logout() : window.location.assign('/acceso'));
document.querySelector('#authClose').addEventListener('click', () => authDialog.close()); document.querySelector('.dialog-close:not(#authClose)').addEventListener('click', () => bidDialog.close());
document.querySelectorAll('[data-auth-view]').forEach((button) => button.addEventListener('click', () => openAuth(button.dataset.authView)));
document.querySelectorAll('[data-toggle]').forEach((button) => button.addEventListener('click', () => { const input = document.querySelector(`#${button.dataset.toggle}`); const visible = input.type === 'text'; input.type = visible ? 'password' : 'text'; button.textContent = visible ? 'Mostrar' : 'Ocultar'; }));
document.querySelector('#registerPassword').addEventListener('input', (event) => passwordStrength(event.target.value));
document.querySelector('#loginForm').addEventListener('submit', async (event) => { event.preventDefault(); const response = await fetch('/api/auth/login', { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ username: document.querySelector('#loginUsername').value, password: document.querySelector('#loginPassword').value }) }); const result = await response.json(); if (!response.ok) { document.querySelector('#loginFeedback').textContent = result.error; return; } setSession(result.user); authDialog.close(); event.target.reset(); });
document.querySelector('#registerForm').addEventListener('submit', async (event) => { event.preventDefault(); const payload = { username: document.querySelector('#registerUsername').value, email: document.querySelector('#registerEmail').value, firstName: document.querySelector('#registerFirstName').value, lastName: document.querySelector('#registerLastName').value, phone: document.querySelector('#registerPhone').value, birthDate: document.querySelector('#registerBirthDate').value, password: document.querySelector('#registerPassword').value }; const response = await fetch('/api/auth/register', { method: 'POST', headers: authHeaders(true), body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) { document.querySelector('#registerFeedback').textContent = result.error; return; } setSession(result.user); authDialog.close(); event.target.reset(); passwordStrength(''); });
document.querySelector('#searchForm').addEventListener('submit', async (event) => { event.preventDefault(); await loadProducts(document.querySelector('#searchInput').value.trim()); document.querySelector('#explorar').scrollIntoView({ behavior: 'smooth' }); renderRecommendation(); });
document.querySelectorAll('[data-category]').forEach((button) => button.addEventListener('click', async () => { document.querySelector('.categories .active').classList.remove('active'); button.classList.add('active'); state.category = button.dataset.category; await loadProducts(); renderRecommendation(); }));
document.querySelector('#bidForm').addEventListener('submit', async (event) => { event.preventDefault(); const response = await fetch('/api/bids', { method: 'POST', headers: authHeaders(true), body: JSON.stringify({ productId: document.querySelector('#bidProductId').value, amount: Number(document.querySelector('#bidAmount').value) }) }); const result = await response.json(); document.querySelector('#bidFeedback').textContent = result.message || result.error; if (response.ok) { await loadProducts(); renderRecommendation(); setTimeout(() => bidDialog.close(), 1300); } else if (response.status === 401) { bidDialog.close(); window.location.assign(`/acceso?destino=oferta&producto=${encodeURIComponent(document.querySelector('#bidProductId').value)}`); } });
document.querySelector('#refreshRecommendations').addEventListener('click', renderRecommendation); document.querySelector('#productSelect').addEventListener('change', fillProductForm);
document.querySelector('#productForm').addEventListener('submit', async (event) => { event.preventDefault(); const productId = document.querySelector('#productSelect').value; const payload = { title: document.querySelector('#productTitle').value, category: document.querySelector('#productCategory').value, currentBid: Number(document.querySelector('#productBid').value), badge: document.querySelector('#productBadge').value }; const response = await fetch(`/api/products/${productId}`, { method: 'PATCH', headers: authHeaders(true), body: JSON.stringify(payload) }); const result = await response.json(); document.querySelector('#productFeedback').textContent = result.product ? 'Producto actualizado correctamente.' : result.error; if (response.ok) { await loadProducts(); renderRecommendation(); } });
document.querySelector('#userForm').addEventListener('submit', async (event) => { event.preventDefault(); const payload = { username: document.querySelector('#newUsername').value, email: document.querySelector('#newEmail').value, firstName: document.querySelector('#newFirstName').value, lastName: document.querySelector('#newLastName').value, phone: document.querySelector('#newPhone').value, birthDate: document.querySelector('#newBirthDate').value, password: document.querySelector('#newPassword').value, role: document.querySelector('#newRole').value }; const endpoint = state.editingUser ? `/api/users/${encodeURIComponent(state.editingUser)}` : '/api/users'; const response = await fetch(endpoint, { method: state.editingUser ? 'PATCH' : 'POST', headers: authHeaders(true), body: JSON.stringify(payload) }); const result = await response.json(); document.querySelector('#userFeedback').textContent = result.user ? 'Usuario guardado correctamente.' : result.error; if (response.ok) { resetUserForm(); loadUsers(); } });

loadProducts().then(() => { renderRecommendation(); const pendingProduct = new URLSearchParams(window.location.search).get('oferta'); const product = state.products.find((item) => item.id === pendingProduct); if (state.currentUser && product) { window.history.replaceState({}, '', '/'); openBid(product); } }); updateSessionUI();
